"""empty message

Revision ID: 104fd46b6b3e
Revises: 
Create Date: 2019-05-03 11:31:53.680675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104fd46b6b3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('programmes', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'programmes')
    # ### end Alembic commands ###
